### ISSUE TITLE
Support typed properties

### ISSUE THREAD

**Issue by kleivane** [Cantara/property-config#8]
Add convenience-functions when getting properties 

Ie.
`getAsInteger(), getAsString`

**Comment by kleivane** [comment]
@totto was thinking about this; this is meant to be pure convenice functions, and not add validation of the type conversion on startup, right? 

So suggested fix; 
We keep the current `String get(String key)` implementation, but add only new typed methods
`Integer getAsInteger(String key)` that raises an exeption when type conversion fails.

**Comment by kimcs** [comment]
This is now implemented.
